config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  get 'users/destroy'

  devise_for :users

  resources :projects do
    resources :comments
  end

  resources :users
  get 'landingpage/landingpage'
  root to: 'landingpage#landingpage'

  get "/404", :to => "errors#not_found"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :name, :presence => true
  validates :body, length: {minimum: 1, maximum: 500, :message => "Body must be between 1 and 500 characters."}
  validates :user, :presence => true
  validates :project, :presence => true
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :cover, CoverUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :project_tags
  has_many :tags, :through => :project_tags

  validates :title, length: {minimum: 3, maximum: 50, :message => ": Length must be in range 3-50 characters"}
  validates :description, length: {minimum: 10, maximum: 30000, :message => ": Length must be in range 10-30000 characters"}
  validates :contact, length: {minimum: 8, maximum: 250, :message => ": Length must be in range 8-250 characters"}
  validates :user, :presence => true
end

app/models/project_tag.rb
class ProjectTag < ApplicationRecord
  belongs_to :project
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :project_tags
  has_many :projects, :through => :project_tags

  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, CoverUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true
  validates_format_of :username, with: /\A[a-z0-9_-]{3,15}\z/, :message => ": No uppercase letters and length in range 3-15 characters"
  validates :username, uniqueness: true, if: -> { self.username.present? }

  validates_format_of :first_name, with: /\A[A-Z][-a-zA-Z]{1,29}\z/i, :message => ": Length must be in range 2-30 characters"
  validates_format_of :last_name, with: /\A[A-Z][-a-zA-Z]{1,29}\z/i, :message => ": Length must be in range 2-30 characters"
  validates_format_of :email, with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, :message => ": Not a valid email. example: 'name@emailprovider.something'"

  has_many :projects, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:first_name, :last_name, :username, :company_name, :email, :password, tag_ids:[])
    end

    devise_parameter_sanitizer.permit(:sign_in) do |user|
      user.permit(:email, :password)
    end

    devise_parameter_sanitizer.permit(:account_update) do |user|
      user.permit(:first_name, :last_name, :username, :about, :skills, :company_name, :email, :password, :current_password, :image, :image_cache, :remove_image, tag_ids:[])
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :special_auth, only: [:new]
  before_action :authenticate_user!, except: [:show]

  respond_to :html, :js

  def create
    @project = Project.find(params[:project_id])
    @comment = @project.comments.create(params[:comment].permit(:name, :body, :user_id))
    redirect_to project_path(@project)
  end

  def destroy
    @project = Project.find(params[:project_id])
    @comment = @project.comments.find(params[:id])
    @comment.destroy
    redirect_to project_path(@project)
  end

  def new
    @project = Project.find(params[:project_id])
  end

  def special_auth
    if !user_signed_in?
      render :js => "window.location = '#{new_user_session_path}'"
    end
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render :status => 404
  end

end

app/controllers/landingpage_controller.rb
class LandingpageController < ApplicationController
  def landingpage
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  respond_to :html, :js

  # GET /projects
  # GET /projects.json
  def index
    @q = Project.search(params[:q])
    @projects = @q.result(distinct: true).reverse_order.paginate(:page => params[:page], per_page: 5)

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :cover, :contact, tag_ids:[])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @q = User.search(params[:q])
    @users = @q.result(distinct: true).reverse_order.paginate(:page => params[:page], per_page: 5)
  end

  def destroy
    @user = current_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landingpage_helper.rb
module LandingpageHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Submitted by: <%= comment.name %></h3>
      </div>
      <div class="panel-body">
        <%= comment.body %>
      </div>
      <div class="panel-footer">
        <%= time_ago_in_words(comment.created_at) %>
        <% if user_signed_in? && comment.user_id == current_user.id %>
            <%= link_to 'delete', project_comment_path(comment.project_id, comment), method: :delete, data: {confirm: 'Are you sure you want to delete comment'} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@project, @project.comments.build]) do |f| %>
  <div class="field">
    <%= f.hidden_field :name, :value => current_user.first_name %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br>
<% end %>

app/views/comments/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>New Project</h2>

      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/comments/new.js.erb
$('#new_comment').hide().after('<%= j render "form" %>')

app/views/landingpage/landingpage.html.erb
<!-- Heading Row START -->
<div class="row landingpage-head">


  <div class="container">
    <div class="jumbotron transparent">
      <h1><span>Westerhub</span></h1><br>
        <h3><span>Got a great idea, but need a team?</span></h3>
        <h3><span>Or eager to join said team?</span></h3>
        <h3><span>Westerhub got your back!</span></h3>
    </div>
  </div>

</div>

<hr>
<!-- Heading Row END-->


<div class="container">

  <!--Slogan element START-->
  <div class="row">
    <div class="col-lg-12">
      <div class="well text-center">
        <% if notice %> <div class="alert alert-info"><%= notice %></div> <% end %>
        <% if alert %> <div class="alert alert-warning"><%= alert %></div> <% end %>
        This is a great spot for a business tagline or phone number for easy access!
      </div>
    </div>
  </div>
  <!--Slogan element END-->


  <!--3 columns element START-->
  <div class="row">
    <div class="col-md-4">
      <h2>Projects</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
      <%= link_to 'Projects', projects_path, :class => "btn btn-default" %>
    </div>
    <!-- /.col-md-4 -->
    <div class="col-md-4">
      <h2>Collaborators</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
      <%= link_to 'Collaborators', users_path, :class => "btn btn-default" %>
    </div>
    <!-- /.col-md-4 -->
    <div class="col-md-4">
      <h2>Companies</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe rem nisi accusamus error velit animi non ipsa placeat. Recusandae, suscipit, soluta quibusdam accusamus a veniam quaerat eveniet eligendi dolor consectetur.</p>
      <a class="btn btn-default" href="#">More Info</a>
    </div>
    <!-- /.col-md-4 -->
  </div>
  <!--3 columns element END-->


  <!--FEEDBACKS START-->
  <!--first feedback-->
  <hr class="section-heading-spacer">
  <div class="content-section-a">
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-sm-6">
          <div class="clearfix"></div>
          <h2 class="section-heading">Joakim E Jacobsen<br></h2>
          <h3>Authentication, Comments, Collaborators</h3>
          <blockquote class="blockquote">
            <p class="mb-0">"In addition to focusing on authentication through the Devise gem and validating user input on login/sign in, I was also responsible for implementing the landingpage, comments on projects, and the footer."</p>
            <footer class="blockquote-footer">Joakim E Jacobsen, <cite title="Source Title">Westerdals Oslo ACT</cite></footer>
          </blockquote>
        </div>
        <div class="col-lg-5 col-lg-offset-2 col-sm-6">
          <%= image_tag "3.png", :class => "featurette-image img-circle img-responsive pull-right" %>
        </div>
      </div>

    </div>
    <!-- /.container -->
  </div>
  <!--first feedback END-->
  <hr class="section-heading-spacer">
  <!--second feedback START-->
  <div class="content-section-b">
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">

          <div class="clearfix"></div>
          <h2 class="section-heading">Eva Dahloe</h2>
          <h3>AJAX, Design, Validation</h3>
          <blockquote class="blockquote">
            <p class="mb-0">"Responsibilities included working with AJAX, and designing the pages for projects.
              Also implemented features for sorting and searching, uploading images, and worked with validation of the project and comment models."</p>
              <footer class="blockquote-footer">Eva Dahloe, <cite title="Source Title">Westerdals Oslo ACT</cite></footer>
            </blockquote>
        </div>
        <div class="col-lg-5 col-sm-pull-6  col-sm-6">
          <%= image_tag "2.png", :class => "featurette-image img-circle img-responsive pull-left" %>
        </div>
      </div>

    </div>
    <!-- /.container -->
  </div>
  <!--second feedback END-->
  <!--third feedback START-->
  <hr class="section-heading-spacer">
  <div class="content-section-a">
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-sm-6">
          <div class="clearfix"></div>
          <h2 class="section-heading">Nikita Zhevnitskiy<br></h2>
          <h3>Testing, Docker, Travis, Heroku</h3>
          <blockquote class="blockquote">
            <p class="mb-0">"Main responsibility was testing: unit, integration, controllers and test coverage reports.
              Additional responsibilities were continuous integration, configuration of docker images, travis and deployment to heroku."</p>
            <footer class="blockquote-footer">Nikita Zhevnitskiy, <cite title="Source Title">Westerdals Oslo ACT</cite></footer>
          </blockquote>
        </div>
        <div class="col-lg-5 col-lg-offset-2 col-sm-6">
          <%= image_tag "1.png", :class => "featurette-image img-circle img-responsive pull-right" %>
        </div>
      </div>

    </div>
    <!-- /.container -->
  </div>
  <!--third feedback END-->
  <hr class="section-heading-spacer">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Westerhub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>

    <!--Render nav bar -->
    <%= render partial: "shared/navbar" %>

    <% if current_page?(root_url) %>
      <%= yield %>
    <% else %>
      <div class="container">
        <% if notice %> <div class="alert alert-info"><%= notice %></div> <% end %>
        <% if alert %> <div class="alert alert-warning"><%= alert %></div> <% end %>
        <%= yield %>
      </div>
    <% end %>
    <!--Render nav bar -->
    <%= render partial: "shared/footer" %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>

  <!-- Errors start -->
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h4>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Errors end -->


  <div class="form-group" id="project-form">
    <%= f.label :title %>
    <%= f.text_field :title, class:"form-control"%>

    <%= f.label :description %>
    <%= f.text_area :description,size:"2x10",:class=>'form-control' %>

    <%= f.label :contact %>
    <%= f.text_field :contact, class:"form-control"%>

    <div class="field">
      <%= f.label "Department" %><br />
      <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |b| %>
          <div class="collection-check-box">
            <%= b.check_box %>
            <%= b.label %>
          </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :cover %>
      <%= f.file_field :cover %>
    </div>

    <div id="btn-sbmt-new-proj" class="row-of-elements">
      <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>

    <div class="row-of-elements">
      <%= link_to 'Back', request.referer, :class => 'btn btn-primary' %>
    </div>

  </div>

<% end %>

app/views/projects/_index_projects.html.erb
<% @projects.each do |project| %>

  <div class="row">
    <% if project.cover?%>
        <div class="col-sm-9 text-left">
    <% else %>
        <div class="col-sm-12 text-left">
    <% end %>

    <h2><%= project.title %></h2>
    <p>Publisher: <%= User.find(project.user_id).first_name %> <%= User.find(project.user_id).last_name %></p>
    <p><%= truncate(project.description, length: 200, separator: ' ') %></p>

    <% project.tags.each do |tag| %>
        <p class="department" id="department<%= tag.cssName %>"><%= tag.name %></p>
    <% end %>

    <br>
    <%= link_to 'Show', project, class:"btn btn-primary" %>
    </div>

    <% if project.cover?%>
        <div class="col-sm-3 project-row-img">
          <%= image_tag project.cover.thumb.url, :class => 'global-img-round-edges' %>
        </div>
    <% end %>

    </div>
    <hr>
  <% end %>

  <%= will_paginate @projects, renderer: BootstrapPagination::Rails %>
</div>

app/views/projects/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Editing Project</h1>

  <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<div class="container-fluid">
  <div class="row content">

    <!--LEFT SIDEBAR start-->
    <div class="col-sm-2 global-left-bar">
      <div class="row" id="create-project">
        <legend>Create project</legend>
        <%= link_to 'New project', new_project_path, class:"btn btn-primary" %>
      </div>

      <fieldset class="row search-field">
        <legend>Sort by department</legend>
        <%= search_form_for @q, :remote => true do |f| %>

            <div class="field">
              <%= f.collection_check_boxes :tags_id_in_any, Tag.all, :id, :name do |b| %>
                  <div class="collection-check-box">
                    <%= b.check_box %>
                    <%= b.label %>
                  </div>
              <% end %>
              <br>
            </div>

            <div class="field">
              <%= f.label :title_cont, "Title contains:" %>
              <br>
              <%= f.text_field :title_cont, id: 'search-projects-field' %>
            </div>

            <br>

            <div class="actions"><%= f.submit "Search" %></div>
        <% end %>
      </fieldset>

    </div>
    <!--LEFT SIDEBAR end-->

    <!--CONTENT START -->
    <div class="col-sm-8">

      <div id="projects_form">
        <%= render partial: 'projects/index_projects'%>
      </div>

    <!-- CONTENT END -->

    <!--RIGHT SIDEBAR start-->
      <div class="col-sm-2 global-right-bar">

        <div class="well">
          <p>ADS</p>
        </div>

        <div class="well">
          <p>ADS</p>
        </div>

        <div class="well">
          <p>ADS</p>
        </div>
      </div>
      <!--RIGHT SIDEBAR end-->

    </div>
  </div>
</div>

app/views/projects/index.js.erb
$("#projects_form").html("<%= escape_javascript( render(partial: 'projects/index_projects') ) %>");

app/views/projects/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>New Project</h1>

  <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<!-- VERSION 3 -->
<!--Based on http://bootsnipp.com/snippets/MRgWB-->
<div class="container">
  <div class="row">

    <!-- Side container -->
    <div class="col-sm-2 global-left-bar">
      <% user = User.find(@project.user_id) %>
      <% image = user.image.thumb.url %>
      <div class="row" >
        <% if !image.nil? %>
          <%= link_to image_tag(image, :class => 'global-img-round-edges'), user %>
        <% end %>
      </div>
      <div class="row">
        <h4>Name: </h4>
        <p id="project-user-name"><%= user.first_name %> <%= user.last_name %></p>
      </div>
      <div class="row">
        <h4>Introduction:</h4>
        <p><%= user.about %></p>
      </div>
    </div>

    <!-- Project -->
    <div class="col-sm-8" id="project-container">

      <!-- Heading -->
      <div class="row" id="project-heading">
        <div class="col-sm-9">
          <p class="row-of-elements">Published: <%= @project.created_at.to_date %></p>
          <% if user_signed_in? && @project.user_id == current_user.id %>
              <div id="editing-buttons" class="row-of-elements">
                <%= link_to 'Edit', edit_project_path(@project),  class: 'btn btn-primary row-of-elements'%>
                <%= link_to 'Delete', @project, class: 'btn btn-primary row-of-elements', method: :delete, data: {confirm: 'Are you sure?' } %>
              </div>
          <% end %>

          <h2><%= @project.title %></h2>
          <% @project.tags.each do |tag| %>
              <p class="department" id="department<%= tag.cssName %>"><%= tag.name %></p>
          <% end %>
        </div>

        <!-- Show picture if present -->
        <div class="col-sm-3">
          <% if @project.cover? %>

              <div data-toggle="modal" data-target="#modal">
                <%= image_tag @project.cover.thumb.url, :class => 'global-img-round-edges', :id => 'show-project-img' %>
              </div>

              <div id="modal" class="modal fade" role="dialog">
                <div class="modal-dialog modal-sm">

                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                      <%= image_tag @project.cover.url %>
                    </div>
                  </div>

                </div>
              </div>
          <% end %>
        </div>
      </div>
      <!-- Heading end -->

      <div class="row project-info">
        <h4>Summary</h4>
        <%= @project.description %>
      </div>

      <div class="row project-info" id="contact">
        <h4>Contact information</h4>
        <%= @project.contact %>
      </div>

      <!--Comments section-->
      <br>
      <div class="row">
        <div class="col-sm-5 pull-left">
          <h3><%= @project.comments.count %> Comments</h3>
        </div>
        <div class="col-sm-3 pull-right list-content">
          <%= link_to 'New Comment', new_project_comment_path(@project), id: "new_comment", remote: true, class:"btn btn-primary" %>
        </div>
        <div class="col-sm-8" id="myForm">

        </div>
      </div>
      <%= render @project.comments %>
      <br>
    </div>
    <!-- Project end -->

    <!--RIGHT SIDEBAR start-->
    <div class="col-sm-2 global-right-bar">

      <div class="well">
        <p>ADS</p>
      </div>

      <div class="well">
        <p>ADS</p>
      </div>

      <div class="well">
        <p>ADS</p>
      </div>
    </div>
    <!--RIGHT SIDEBAR end-->

  </div>
</div>

app/views/shared/_footer.html.erb
<!--FOOTER START-->
<div class="footer">
  <section style="height:80px;"></section>
  <div class="row" style="text-align:center;">
  </div>
  <!----------- Footer ------------>
  <footer class="footer-bs">
    <div class="row">
      <div class="col-md-4 footer-brand animated fadeInLeft" id="footerTopPadding" style="text-align:center;">
        <%= image_tag "footer_logo/westerhub-200.png"%>
        <p>The purpose of the Westerhub is to create a meeting place where inspired people can come together and create something amazing.
         In addition we also want to broadcast our amazing users to cool companies out there. This is solved by allowing companies to create
         profiles and join in on the fun.</p>
        <p>If you have any questions or requests which our hub does not currently facilitate, don't hesitate to send us an email</p>
      </div>
      <div class="col-md-4 footer-nav animated fadeInUp" id="footerTopPadding" style="text-align:center;">
        <%= image_tag "github-128.png" %>
        <h4>Our github accounts</h4>
        <div class="col-md-12">
          <ul class="pages">
            <li><a href="https://github.com/JoakimEJ">Joakim E Jacobsen</a></li>
            <li><a href="https://github.com/NikitaZhevnitskiy">Nikita Zhevnitskiy</a></li>
            <li><a href="https://github.com/dem92">Eva Dahloe</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4 footer-ns animated fadeInRight">
        <iframe width="100%" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed/v1/view?key=AIzaSyDJKzkT7QF6dSogCjjvdyzCGBm5_zGmcGQ&center=59.9160,10.7597&zoom=18&maptype=satellite"></iframe>
      </div>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<!--Navbar template START-->
  <nav class=
         <% if current_page? (root_url) %>
           "navbar navbar-landing">
         <% else %>
           "navbar navbar-default">
         <% end %>
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Westerhub", root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Projects", projects_path %> </li>
        <li> <%= link_to 'Collaborators', users_path %> </li>
        <li><a href="#">Companies</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
            <li><%= link_to current_user.email, user_path(current_user.id) %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--Navbar template END-->

app/views/users/show.html.erb
<h2>Profile: <%= @user.first_name + " " + @user.last_name %></h2>

<div class="panel panel-info">

  <div class="panel-heading">
    <h3 class="panel-title">Name</h3>
  </div>
  <div class="panel-body">
      <%= @user.first_name %> <%= @user.last_name %>
  </div>


  <div class="panel-heading">
    <h3 class="panel-title">About</h3>
  </div>
  <div class="panel-body">
    <%= @user.about %>
  </div>

  <div class="panel-heading">
    <h3 class="panel-title">Skills</h3>
  </div>
  <div class="panel-body">
    <%= @user.skills %>
  </div>


  <div class="panel-heading">
    <h3 class="panel-title">Areas of expertise</h3>
  </div>
  <div class="panel-body">
    <% @user.tags.each do |tag| %>
        <p class="department" id="department<%= tag.cssName %>"><%= tag.name %></p>
    <% end %>
  </div>


  <div class="panel-heading">
    <h3 class="panel-title">Contact</h3>
  </div>
  <div class="panel-body">
    <%= @user.email %>
  </div>

  <div class="panel-heading">
    <h3 class="panel-title">Image</h3>
  </div>
  <% if @user.image.thumb.url!=nil %>
    <div class="panel-body">
      <%= image_tag @user.image.thumb.url, :class => "global-img-round-edges" %>
    </div>
  <% end %>

</div>

<% if user_signed_in? %>
    <% if @user.id == current_user.id %>
        <%= link_to 'Edit profile', edit_user_registration_path, class:"btn btn-primary" %>
        <%= link_to 'Destroy', current_user, class:"btn btn-primary", method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
<% end %>